# Generated by Django 4.1.1 on 2022-09-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dictionary_options_alter_users_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='data',
            new_name='date',
        ),
    ]
