# Generated by Django 4.1.1 on 2022-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_data_users_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
